Run all js tests:
  $ ecma-sl test --harness=harness.js . | grep "\S" | sed '/^[^.]/d' | sed 's/ \[.*\]//g' | sort -h
  ./array/array.js .............................. SUCCESS
  ./array/array_cons_length.js .................. SUCCESS
  ./array/array_sort.js ......................... SUCCESS
  ./harness.js .................................. SUCCESS
  ./object/basic/access.js ...................... SUCCESS
  ./object/basic/constructor.js ................. SUCCESS
  ./object/basic/prop-keys.js ................... SUCCESS
  ./object/basic/prototype.js ................... SUCCESS
  ./object/methods/assign.js .................... SUCCESS
  ./object/methods/create.js .................... SUCCESS
  ./object/methods/define_prop.js ............... SUCCESS
  ./object/methods/freeze.js .................... SUCCESS
  ./object/methods/own_descriptor.js ............ SUCCESS
  ./regex/regex_1.js ............................ SUCCESS
  ./regex/regex_10.js ........................... SUCCESS
  ./regex/regex_11.js ........................... SUCCESS
  ./regex/regex_12.js ........................... SUCCESS
  ./regex/regex_13.js ........................... SUCCESS
  ./regex/regex_14.js ........................... SUCCESS
  ./regex/regex_15.js ........................... SUCCESS
  ./regex/regex_16.js ........................... SUCCESS
  ./regex/regex_17.js ........................... SUCCESS
  ./regex/regex_18.js ........................... SUCCESS
  ./regex/regex_19.js ........................... SUCCESS
  ./regex/regex_2.js ............................ SUCCESS
  ./regex/regex_20.js ........................... SUCCESS
  ./regex/regex_21.js ........................... SUCCESS
  ./regex/regex_22.js ........................... SUCCESS
  ./regex/regex_23.js ........................... SUCCESS
  ./regex/regex_24.js ........................... SUCCESS
  ./regex/regex_25.js ........................... SUCCESS
  ./regex/regex_26.js ........................... SUCCESS
  ./regex/regex_27.js ........................... SUCCESS
  ./regex/regex_28.js ........................... SUCCESS
  ./regex/regex_29.js ........................... SUCCESS
  ./regex/regex_3.js ............................ SUCCESS
  ./regex/regex_30.js ........................... SUCCESS
  ./regex/regex_31.js ........................... SUCCESS
  ./regex/regex_32.js ........................... SUCCESS
  ./regex/regex_33.js ........................... SUCCESS
  ./regex/regex_34.js ........................... SUCCESS
  ./regex/regex_35.js ........................... SUCCESS
  ./regex/regex_36.js ........................... SUCCESS
  ./regex/regex_37.js ........................... SUCCESS
  ./regex/regex_38.js ........................... SUCCESS
  ./regex/regex_39.js ........................... SUCCESS
  ./regex/regex_4.js ............................ SUCCESS
  ./regex/regex_40.js ........................... SUCCESS
  ./regex/regex_41.js ........................... SUCCESS
  ./regex/regex_42.js ........................... SUCCESS
  ./regex/regex_43.js ........................... SUCCESS
  ./regex/regex_44.js ........................... SUCCESS
  ./regex/regex_45.js ........................... SUCCESS
  ./regex/regex_46.js ........................... SUCCESS
  ./regex/regex_47.js ........................... SUCCESS
  ./regex/regex_48.js ........................... SUCCESS
  ./regex/regex_49.js ........................... SUCCESS
  ./regex/regex_5.js ............................ SUCCESS
  ./regex/regex_50.js ........................... SUCCESS
  ./regex/regex_51.js ........................... SUCCESS
  ./regex/regex_52.js ........................... SUCCESS
  ./regex/regex_53.js ........................... SUCCESS
  ./regex/regex_54.js ........................... SUCCESS
  ./regex/regex_55.js ........................... SUCCESS
  ./regex/regex_56.js ........................... SUCCESS
  ./regex/regex_57.js ........................... SUCCESS
  ./regex/regex_58.js ........................... SUCCESS
  ./regex/regex_59.js ........................... SUCCESS
  ./regex/regex_6.js ............................ SUCCESS
  ./regex/regex_60.js ........................... SUCCESS
  ./regex/regex_61.js ........................... SUCCESS
  ./regex/regex_62.js ........................... SUCCESS
  ./regex/regex_63.js ........................... SUCCESS
  ./regex/regex_64.js ........................... SUCCESS
  ./regex/regex_65.js ........................... SUCCESS
  ./regex/regex_66.js ........................... SUCCESS
  ./regex/regex_67.js ........................... SUCCESS
  ./regex/regex_68.js ........................... SUCCESS
  ./regex/regex_69.js ........................... SUCCESS
  ./regex/regex_7.js ............................ SUCCESS
  ./regex/regex_70.js ........................... SUCCESS
  ./regex/regex_71.js ........................... SUCCESS
  ./regex/regex_72.js ........................... SUCCESS
  ./regex/regex_73.js ........................... SUCCESS
  ./regex/regex_74.js ........................... SUCCESS
  ./regex/regex_75.js ........................... SUCCESS
  ./regex/regex_8.js ............................ SUCCESS
  ./regex/regex_9.js ............................ SUCCESS
  ./regex/regex_utf16.js ........................ FAILURE
  ./simple/catch.js ............................. SUCCESS
  ./simple/destructuring.js ..................... SUCCESS
  ./simple/events.js ............................ SUCCESS
  ./simple/flow.js .............................. SUCCESS
  ./simple/forin.js ............................. SUCCESS
  ./simple/function.js .......................... SUCCESS
  ./simple/json.js .............................. SUCCESS
  ./simple/log.js ............................... SUCCESS
  ./simple/map.js ............................... SUCCESS
  ./simple/object.js ............................ SUCCESS
  ./simple/primes.js ............................ SUCCESS
  ./simple/queue.js ............................. SUCCESS
  ./simple/string.js ............................ SUCCESS
  ./simple/variable.js .......................... SUCCESS
